name: Trigger Existing Azure Pipeline

on:
  workflow_dispatch:
    inputs:
      orgName:
        description: 'Enter your Azure DevOps Organization name'
        required: true
      projectName:
        description: 'Enter your Azure DevOps Project name'
        required: true
      targetRepositoryName:
        description: 'Enter the target repository name'
        required: true
      ResourceYamlFile:
        description: 'Select the resource YAML file'
        required: true

jobs:
  # Display input values for debugging
  display-input-values:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input Values
        run: |
          echo "orgName: ${{ github.event.inputs.orgName }} "
          echo "projectname: ${{ github.event.inputs.projectName }}"
          echo "ResourceYamlFile": ${{ github.event.inputs.ResourceYamlFile }}"
          echo "targetRepositoryName": ${{ github.event.inputs.targetRepositoryName }}"
  build-in-actions-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Azure Login using Service Principal
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Trigger an Existing Azure Pipeline
      uses: Azure/pipelines@releases/v1
      with:
          azure-devops-project-url: 'https://dev.azure.com/${{ github.event.inputs.orgName }}/${{ github.event.inputs.projectName }}'
          azure-pipeline-name: ${{ github.event.inputs.targetRepositoryName }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          parameters: |
            {
              "ResourceYamlFile": "${{ ${{ github.event.inputs.ResourceYamlFile }} }}",
              "targetRepositoryName": "${{ ${{ github.event.inputs.targetRepositoryName }} }}"
            }
